eight_points_guzzle:
    logging: "%kernel.debug%"

    clients:
        reddit:
            base_url: "https://api.reddit.com"

            options:
                timeout: 30

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: "EightpointsGuzzleBundle/7.0"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~